name: Release and publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  release-and-publish:
    name: Create Release and Publish Crate
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git-cliff
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test --all-features

      - name: Run clippy
        run: cargo clippy --all-features -- -D warnings

      - name: Check formatting
        run: cargo fmt --check

      - name: Get current version
        id: current-version
        run: |
          current_version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          echo "version=$current_version" >> $GITHUB_OUTPUT

      - name: Calculate next version using git-cliff
        id: next-version
        run: |
          # Use git-cliff to calculate next version based on conventional commits
          current_version="${{ steps.current-version.outputs.version }}"
          echo "Current version: $current_version"
          
          # Calculate next version using git-cliff's bump functionality
          next_version=$(git cliff --bumped-version)
          
          # If git-cliff returns nothing, no version bump is needed
          if [ -z "$next_version" ] || [ "$next_version" = "$current_version" ]; then
            echo "No version bump needed - no conventional commits found"
            echo "skip_release=true" >> $GITHUB_OUTPUT
            echo "version=$current_version" >> $GITHUB_OUTPUT
          else
            echo "Next version (calculated by git-cliff): $next_version"
            echo "skip_release=false" >> $GITHUB_OUTPUT
            echo "version=$next_version" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Cargo.toml version
        if: steps.next-version.outputs.skip_release != 'true'
        run: |
          next_version="${{ steps.next-version.outputs.version }}"
          sed -i "s/^version = \".*\"/version = \"$next_version\"/" Cargo.toml
          echo "Updated Cargo.toml to version $next_version"

      - name: Build release binary
        if: steps.next-version.outputs.skip_release != 'true'
        run: cargo build --release

      - name: Dry run publish
        if: steps.next-version.outputs.skip_release != 'true'
        run: cargo publish --dry-run --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Generate changelog
        id: changelog
        if: steps.next-version.outputs.skip_release != 'true'
        run: |
          next_version="${{ steps.next-version.outputs.version }}"
          # Generate changelog for this version
          git cliff --tag "$next_version" --unreleased --prepend CHANGELOG.md
          
          # Extract release notes for GitHub release
          git cliff --tag "$next_version" --unreleased --strip all > release_notes.md
          
          echo "Generated changelog and release notes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit version bump and changelog
        if: steps.next-version.outputs.skip_release != 'true'
        run: |
          next_version="${{ steps.next-version.outputs.version }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Cargo.toml CHANGELOG.md
          git commit -m "chore: bump version to $next_version

          - Update Cargo.toml version to $next_version
          - Update CHANGELOG.md with release notes"
          git tag "$next_version"

      - name: Push changes and tags
        if: steps.next-version.outputs.skip_release != 'true'
        run: |
          git push origin main
          git push origin --tags

      - name: Create GitHub Release
        id: create-release
        if: steps.next-version.outputs.skip_release != 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.next-version.outputs.version }}
          release_name: Release ${{ steps.next-version.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: false

      - name: Upload release binary
        if: steps.next-version.outputs.skip_release != 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: target/release/pnger
          asset_name: pnger-linux-x86_64
          asset_content_type: application/octet-stream

      - name: Publish to crates.io
        if: steps.next-version.outputs.skip_release != 'true'
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Post-publish verification
        if: steps.next-version.outputs.skip_release != 'true'
        run: |
          echo "✅ Release ${{ steps.next-version.outputs.version }} created successfully"
          echo "✅ Changelog generated and updated"
          echo "✅ Crate published to crates.io"
          echo "✅ Binary uploaded to GitHub release"
          echo ""
          echo "🔗 Release URL: ${{ steps.create-release.outputs.html_url }}"
          echo "📦 Crate URL: https://crates.io/crates/pnger/${{ steps.next-version.outputs.version }}"
          echo "📝 Changelog: Updated CHANGELOG.md with conventional commit parsing"
      
      - name: No release needed
        if: steps.next-version.outputs.skip_release == 'true'
        run: |
          echo "ℹ️ No release needed - no conventional commits found since last release"
          echo "Current version ${{ steps.current-version.outputs.version }} is up to date"
